---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |
    {
      "$schema": "https://docs.renovatebot.com/renovate-schema.json",
      "platform": "gitea",
      "endpoint": "https://forge.${DOMAIN}/api/v1",
      "gitAuthor": "Renovate Bot <renovate@${DOMAIN}>",
      "autodiscover": true,
      "onboarding": true,
      "onboardingConfig": {
        "extends": ["config:recommended"]
      },
      "requireConfig": "optional",
      "repositoryCache": "enabled",
      "persistRepoData": true,
      "allowedCommands": [".*"]
    }
