---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - extract:
        key: renovate
