---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: onepassword-connect
spec:
  namespaceSelector:
    matchNames:
      - external-secrets
  selector:
    matchLabels:
      app.kubernetes.io/name: connect
      app.kubernetes.io/instance: onepassword-connect
  endpoints:
    - port: connect-api
      path: /metrics
      interval: 30s
