---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radicale
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radicale
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        users: "{{ .RADICALE_USERS }}"
  dataFrom:
    - extract:
        key: radicale
