---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ceph-filesystem-ec
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcasts
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: ceph-filesystem-ec
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem-ec
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 55Ti
  storageClassName: ceph-filesystem-ec
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ceph-filesystem-ec
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-incoming
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ceph-filesystem-ec
